name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: squareline-studio-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      # - name: anydesk
      #   shell: cmd
      #   run: |
      #     curl -L -O -J https://download.anydesk.com/AnyDesk.exe &&^
      #     .\AnyDeskStart.cmd
          
      - name: installer
        shell: cmd
        run: |
          curl -L -J --output installer.zip "https://static.squareline.io/downloads/SquareLine_Studio_Windows_v1_2_3.zip" &&^
          7z.exe x installer.zip &&^
          dir
          
      - name: elevate
        shell: cmd
        run: |
          curl -L -J --output elevate.zip "https://github.com/jpassing/elevate/releases/download/1.0/elevate.zip" &&^
          7z.exe x elevate.zip &&^
          dir
          
          
  # set "params=%*"
  # cd /d "%~dp0" && ( if exist "%temp%\getadmin.vbs" del "%temp%\getadmin.vbs" ) && fsutil dirty query %systemdrive% 1>nul 2>nul || (  echo Set UAC = CreateObject^("Shell.Application"^) : UAC.ShellExecute "cmd.exe", "/k cd ""%~sdp0"" && ""%~s0"" %params%", "", "runas", 1 >> "%temp%\getadmin.vbs" && "%temp%\getadmin.vbs" && exit /B ) &&^
  
      - shell: cmd
        run: |
          set CURRENT=%cd%
          echo %CURRENT% &&^
          reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f &&^
          .\bin\x64\Release\Elevate.exe -wait reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 0 /f &&^
          echo disabled &&^
          mkdir C:\installation &&^
          .\bin\x64\Release\Elevate.exe -wait .\SquareLine_Studio_1.2.3_Setup.exe /s /d "C:\installation" &&^
          echo done &&^
          cd /d C:\ &&^
          dir
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
